Asp Net Core Mvc Client/Kartamulia.Accounting.NetCoreMvcClient/ViewModels/Modal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kartamulia.Accounting.NetCoreMvcClient.ViewModels
{
    public class Modal
    {
        #region ctor

        public Modal()
            : base()
        {
        }

        #endregion

        #region Properties

        public string ID { get; set; }

        public string AreaLabelID { get; set; }

        public ModalSize Size { get; set; }

        public string ModalSizeClass
        {
            get
            {
                string modalSize = "modal-sm";

                switch (this.Size)
                {
                    case ModalSize.Small:
                        modalSize = "modal-sm";
                        break;
                    case ModalSize.Large:
                        modalSize = "modal-lg";
                        break;
                    case ModalSize.Medium:
                    default:
                        modalSize = "";
                        break;
                }

                return modalSize;
            }
        }

        #endregion
    }
}

Asp Net Core Mvc Client/Kartamulia.Accounting.NetCoreMvcClient/ViewModels/ModalFooter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kartamulia.Accounting.NetCoreMvcClient.ViewModels
{
    public class ModalFooter
    {
        #region ctor

        public ModalFooter()
            : base()
        {
        }

        #endregion

        #region Properties

        public string SubmitButtonText { get; set; } = "Submit";

        public string CancelButtonText { get; set; } = "Cancel";

        public string SubmitButtonID { get; set; } = "btn-submit";

        public string CancelButtonID { get; set; } = "btn-cancel";

        public bool OnlyCancelButton { get; set; }

        #endregion
    }
}

Asp Net Core Mvc Client/Kartamulia.Accounting.NetCoreMvcClient/ViewModels/ModalHeader.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kartamulia.Accounting.NetCoreMvcClient.ViewModels
{
    public class ModalHeader
    {
        #region ctor

        public ModalHeader()
            : base()
        {
        }

        #endregion

        #region Properties

        public string Heading { get; set; }

        #endregion
    }
}

Asp Net Core Mvc Client/Kartamulia.Accounting.NetCoreMvcClient/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Kartamulia.Accounting.NetCoreMvcClient.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Kartamulia.Accounting.NetCoreMvcClient.Controllers
{
    public class AccountsController : Controller
    {
        private readonly IAccountRepository _accountRepository;

        public AccountsController(IAccountRepository accountRepository)
        {
            _accountRepository = accountRepository;
        }

        public async Task<IActionResult> Index()
        {
            var accounts = await _accountRepository.GetAccountsAsync();
            return View(accounts);
        }
    }
}

Asp Net Core Mvc Client/Kartamulia.Accounting.NetCoreMvcClient/Controllers/GeneralJournalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Kartamulia.Accounting.NetCoreMvcClient.Models;
using Kartamulia.Accounting.NetCoreMvcClient.Repositories;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Kartamulia.Accounting.NetCoreMvcClient.Controllers
{
    public class GeneralJournalsController : Controller
    {
        private readonly IGeneralJournalRepository _generalJournalRepository;

        public GeneralJournalsController(IGeneralJournalRepository generalJournalRepository)
        {
            _generalJournalRepository = generalJournalRepository;
        }

        #region Journal

        public async Task<IActionResult> Index()
        {
            var generalJournals = await _generalJournalRepository.GetGeneralJournalsAsync();
            return View(generalJournals);
        }

        public IActionResult Create()
        {
            object tempDataJournal = null;
            GeneralJournal generalJournal = null;

            if (TempData.TryGetValue("GeneralJournal", out tempDataJournal) == true)
            {
                generalJournal = JsonConvert.DeserializeObject<GeneralJournal>((string)tempDataJournal);
            }
            else
            {
                generalJournal = new GeneralJournal();
                generalJournal.Date = DateTime.Now;
                generalJournal.Description = "Description";
                generalJournal.Reference = "Reference";
            }

            var serializeObject = JsonConvert.SerializeObject(generalJournal);
            TempData["GeneralJournal"] = serializeObject;

            return View(generalJournal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(GeneralJournal generalJournal)
        {
            var taskCode = await Task.FromResult(0);

            if (ModelState.IsValid)
            {
                await _generalJournalRepository.AddOrUpdateGeneralJournalAsync(generalJournal);
                TempData.Clear();
                return RedirectToAction(nameof(Index));
            }
            return View(generalJournal);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create(GeneralJournal generalJournal)
        //{
        //    var taskCode = await Task.FromResult(0);

        //    if (ModelState.IsValid)
        //    {
        //        await _generalJournalRepository.AddOrUpdateGeneralJournalAsync(generalJournal);
        //        TempData.Clear();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(generalJournal);
        //}

        // GET: Journals/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}

            var taskCode = await Task.FromResult(0);

            object tempJournal = null;
            GeneralJournal generalJournal = null;

            if (TempData.TryGetValue("GeneralJournal", out tempJournal) == true)
            {
                generalJournal = JsonConvert.DeserializeObject<GeneralJournal>((string)tempJournal);

                if (generalJournal.Id.Equals(id) == false)
                {
                    generalJournal = await _generalJournalRepository.GetGeneralJournalAsync(id);
                }
            }
            else
            {
                generalJournal = await _generalJournalRepository.GetGeneralJournalAsync(id);
            }

            if (generalJournal == null)
            {
                return NotFound();
            }

            var serializeObject = JsonConvert.SerializeObject(generalJournal);
            TempData["GeneralJournal"] = serializeObject;

            return View(generalJournal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Desciption,Reference")] GeneralJournal generalJournal)
        {
            if (id != generalJournal.Id)
            {
                return NotFound();
            }

            // Test tempdata is still exist
            //
            object tempDataJournal = null;
            if (TempData.TryGetValue("GeneralJournal", out tempDataJournal) == false)
            {
                // TempData exist.
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _generalJournalRepository.AddOrUpdateGeneralJournalAsync(generalJournal);
                }
                catch (Exception)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(generalJournal);
        }

        #endregion

        #region JournalItem

        [HttpGet]
        public async Task<IActionResult> AddEditJournalItem(int id)
        {
            var taskCode = await Task.FromResult(0);

            JournalItem journalItem = null;
            GeneralJournal generalJournal = null;

            if (id != 0)
            {
                // get journal item for edit
            }
            else
            {
                journalItem = new JournalItem();

                object tempDataJournal = null;
                if (TempData.TryGetValue("GeneralJournal", out tempDataJournal) == true)
                {
                    generalJournal = JsonConvert.DeserializeObject<GeneralJournal>((string)tempDataJournal);
                }

                journalItem.JournalId = generalJournal != null ? generalJournal.Id : 0;
            }

            var serializeObject = JsonConvert.SerializeObject(generalJournal);
            TempData["GeneralJournal"] = serializeObject;

            return PartialView("~/Views/GeneralJournals/_FormJournalItem.cshtml", journalItem);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditJournalItem(int id, JournalItem journalItem)
        {
            GeneralJournal generalJournal = null;

            try
            {
                var taskCode = await Task.FromResult(0);

                if (ModelState.IsValid == true)
                {
                    bool isNew = id.Equals(0);

                    if (isNew == true)
                    {
                        object tempJournal = null;

                        if (TempData.TryGetValue("GeneralJournal", out tempJournal) == true)
                        {
                            generalJournal = JsonConvert.DeserializeObject<GeneralJournal>((string)tempJournal);

                            if (generalJournal.Id.Equals(id) == false)
                            {
                                return NotFound();
                            }
                            else
                            {
                                generalJournal.Items.Add(journalItem);
                            }
                        }
                    }
                    else
                    {
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }

            var serializeObject = JsonConvert.SerializeObject(generalJournal);
            TempData["GeneralJournal"] = serializeObject;

            return RedirectToAction(nameof(Create));
        }

        #endregion

    }
}

Asp Net Core Mvc Client/Kartamulia.Accounting.NetCoreMvcClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Net Core Mvc Client</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Accounting Net Core Mvc Client</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Accounts" asp-action="Index">Accounts</a></li>
                    <li><a asp-area="" asp-controller="GeneralJournals" asp-action="Index">General Journals</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Kartamulia Accounting Asp Net Core Mvc Client</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Asp Net Core Mvc Client/Kartamulia.Accounting.NetCoreMvcClient/Views/Shared/_Modal.cshtml
@model Modal

<div aria-hidden="true" aria-labelledby="@Model.AreaLabelID" role="dialog" tabindex="-1" id="@Model.ID" class="modal fade">
    <div class="modal-dialog @Model.ModalSizeClass">
        <div class="modal-content"></div>
    </div>
</div>

Asp Net Core Mvc Client/Kartamulia.Accounting.NetCoreMvcClient/Views/Shared/_ModalFooter.cshtml
@model ModalFooter

<div class="modal-footer">
    @if (Model.OnlyCancelButton == false)
    {
        <button class="btn btn-success" id="@Model.SubmitButtonID" type="submit">
            @Model.SubmitButtonText
        </button>
    }
    <button data-dismiss="modal" id="@Model.CancelButtonID" class="btn btn-default" type="button">@Model.CancelButtonText</button>
</div>

Asp Net Core Mvc Client/Kartamulia.Accounting.NetCoreMvcClient/Views/Shared/_ModalHeader.cshtml
@model ModalHeader

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">@Model.Heading</h4>
</div>

Asp Net Core Mvc Client/Kartamulia.Accounting.NetCoreMvcClient/Views/Shared/_ModalScriptsInit.cshtml
@model string

<script type="text/javascript">
    $(document).ready(function () {

        (function ($) {
            function ModalInit() {
                var $this = this;

                function initializeModel() {
                    $("#@Model").on('loaded.bs.modal', function (e) {
                    }).on('hidden.bs.modal', function (e) {
                        $(this).removeData('bs.modal');
                    });
                }

                $this.init = function () {
                    initializeModel();
                }
            }
            $(function () {
                var self = new ModalInit();
                self.init();
            })
        }(jQuery))
    });
</script>